name: day-03-ci-pipeline for Node.js

on:
  workflow_dispatch:

jobs:
  building:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Day-03-ci-pipeline/example

    steps:

      # Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run linting
      - name: Run linting
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm test

      # Build the project
      - name: Build the project
        run: npm run build

      # Upload the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Day-03-ci-pipeline-artifacts
          path: Day-03-ci-pipeline/example/dist
          retention-days: 5