name: day-07-environments
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  dev:
    name: deploy to dev environment
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: deploy to dev environment
        run: |
          echo "deploying to dev environment"
          echo "environment name: dev"
          echo "deploying to dev environment successfully"
  staging:
    name: deploy to staging environment
    runs-on: ubuntu-latest
    environment: staging
    needs: dev
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: deploy to staging environment
        run: |
          echo "deploying to staging environment"
          echo "environment name: staging"
          echo "deploying to staging environment successfully"
  production:
    name: deploy to production environment
    runs-on: ubuntu-latest
    environment: production
    needs: staging
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: deploy to production environment
        run: |
          echo "deploying to production environment"
          echo "environment name: production"
          echo "deploying to production environment successfully"
