name: secrets-demo
on:
  workflow_dispatch:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secrets
        run: echo "${{ secrets.DOCKER_USER }}"

      - name: successful step
        run: echo "This step will run successfully."

  development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: printing the dev environment secret
        run: echo "${{ secrets.DB_PASSWORD }}"

      - name: printing the dev environment variable
        run: echo "${{ vars.ENV_NAME }}"

  preprod:
    runs-on: ubuntu-latest
    environment: preprod
    steps:
      - name: printing the preprod environment secret
        run: echo "${{ secrets.DB_PASSWORD }}"

      - name: printing the preprod environment variable
        run: echo "${{ vars.ENV_NAME }}"

  production:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: printing the production environment secret
        run: echo "${{ secrets.DB_PASSWORD }}"

      - name: printing the production environment variable
        run: echo "${{ vars.ENV_NAME }}"