name: day-01-variables
on: push
env:
  APP_VERSION: 1.0.0

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: job-level-variable
    steps:
      - name: printing the repository-level variable
        run: echo "application-name: ${{ vars.APP_NAME }}"

      - name: printing the local variable
        run: echo "application version: $APP_VERSION"
        
      - name: printing the step-level variable
        env:
          STEP_VAR: step-level-variable
        run: echo "step variable: $STEP_VAR"