name: day-01-variables

on:
  workflow_dispatch:

env:
  APP_VERSION: "1.0.0"

jobs:
  demo:
    runs-on: ubuntu-latest

    env:
      JOB_VAR: job-level-variable

    steps:
      - name: printing the repository-level variable
        run: echo  "${{ vars.APP_NAME }}"

      - name: printing the workflow-level variable
        run: echo "$APP_VERSION"

      - name: printing the job-level variable
        run: echo "$JOB_VAR"

      - name: printing the step-level variable
        env:
          STEP_VAR: step-level-variable
        run: echo "$STEP_VAR"
