name: day-03-ci-pipeline for Node.js
on:
  workflow_dispatch
jobs:
  building:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Day-03-ci-pipeline/example
    steps:
      # checkout the code
      - name: Checkout the code
        uses: actions/checkout@v4
      # setup Node.js and npm cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./Day-03-ci-pipeline/example/package-lock.json
      # install dependencies
      - name: Install dependencies
        run: npm ci
      # run linting
      - name: Run linting
        run: npm run lint
      # run tests
      - name: Run tests
        run: npm test
      # build the project
      - name: Build the project
        run: npm run build
      # upload the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Day-03-ci-pipeline-artifacts
          path: ./Day-03-ci-pipeline/example/dist
          retention-days: 5
